
# FRONTEND nginx — Deployment + Service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentacar-frontend
  namespace: rentacar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rentacar-frontend

  template:
    metadata:
      labels:
        app: rentacar-frontend
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: rentacar-frontend
          image: ben03030303/rentacar-frontend:latest

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsUser: 101

          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-pid
              mountPath: /var/run
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30

          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"

      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-pid
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: nginx-conf

---

# Service — rentacar-frontend

apiVersion: v1
kind: Service
metadata:
  name: rentacar-frontend
  namespace: rentacar
spec:
  selector:
    app: rentacar-frontend
  ports:
    - port: 80
      targetPort: 8080
